export const SET_BRANCH = "SET_BRANCH";
export const SET_SETTING = "SET_SETTING";

//dashboard
export const SET_DASHBOARD_BLOCKS = "SET_DASHBOARD_BLOCKS";
export const DASHBOARD_BLOCKS_LOADING = "DASHBOARD_BLOCKS_LOADING";
export const SET_DASHBOARD_BALANCE = "SET_DASHBOARD_BALANCE";
export const DASHBOARD_BALANCE_LOADING = "DASHBOARD_BALANCE_LOADING";
export const SET_DASHBOARD_SALES = "SET_DASHBOARD_SALES";
export const DASHBOARD_SALES_LOADING = "DASHBOARD_SALES_LOADING";
export const SET_DASHBOARD_CUSTOMER = "SET_DASHBOARD_CUSTOMER";
export const DASHBOARD_CUSTOMER_LOADING = "DASHBOARD_CUSTOMER_LOADING";
export const SET_DASHBOARD_EXPENSE = "SET_DASHBOARD_EXPENSE";
export const DASHBOARD_EXPENSE_LOADING = "DASHBOARD_EXPENSE_LOADING";
export const SET_DASHBOARD_PROFIT_LOSS = "SET_DASHBOARD_PROFIT_LOSS";
export const DASHBOARD_PROFIT_LOSS_LOADING = "DASHBOARD_PROFIT_LOSS_LOADING";
export const SET_DASHBOARD_EMPLOYEE = "SET_DASHBOARD_EMPLOYEE";
export const DASHBOARD_EMPLOYEE_LOADING = "DASHBOARD_EMPLOYEE_LOADING";
export const SET_DASHBOARD_INCOME = "SET_DASHBOARD_INCOME";
export const DASHBOARD_INCOME_LOADING = "DASHBOARD_INCOME_LOADING";

//transaction
export const SET_ACCOUNT_ALL_VOUCHER = "SET_ACCOUNT_ALL_VOUCHER";
export const ACCOUNT_ALL_VOUCHER_LOADING = "ACCOUNT_ALL_VOUCHER_LOADING";
